import type { Metadata } from "next";
import "./globals.css";
import { BotBar } from "./components/Atoms/BotBar/BotBar";
import { TopBar } from "./components/Atoms/TopBar/TopBar";

export const metadata: Metadata = {
  title: "ForesTCG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-purple-800 text-xl font-semibold flex flex-col h-screen">
        <TopBar />
        {children}
        <BotBar />
      </body>
    </html>
  );
}
